"""empty message

Revision ID: 343381d548bb
Revises: a07ad18156d2
Create Date: 2025-12-11 22:36:39.771452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343381d548bb'
down_revision = 'a07ad18156d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###
