"""empty message

Revision ID: a07ad18156d2
Revises: 9e2c6fbc02aa
Create Date: 2025-12-06 21:45:03.351959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07ad18156d2'
down_revision = '9e2c6fbc02aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assistant_agent_conversation_id', sa.UUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('assistant_agent_conversation_id')

    # ### end Alembic commands ###
