#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@File    : queue_entity.py
"""
from enum import Enum
from uuid import UUID

from pydantic import BaseModel, Field


class QueueEvent(str, Enum):
    """Queue event enum type"""
    LONG_TERM_MEMORY_RECALL = "long_term_memory_recall"  # Long-term memory recall event
    AGENT_THOUGHT = "agent_thought"  # Agent reasoning / thought event
    AGENT_MESSAGE = "agent_message"  # Agent message event
    AGENT_ACTION = "agent_action"  # Agent action event
    DATASET_RETRIEVAL = "dataset_retrieval"  # Dataset/knowledge base retrieval event
    AGENT_END = "agent_end"  # Agent end event
    STOP = "stop"  # Agent stop event
    ERROR = "error"  # Agent error event
    TIMEOUT = "timeout"  # Agent timeout event
    PING = "ping"  # Ping / connectivity event


class AgentThought(BaseModel):
    """Agent reasoning and observation output"""
    id: UUID  # ID of this event; the same event shares the same ID
    task_id: UUID  # Task ID

    # Reasoning and observation of the event
    event: QueueEvent
    thought: str = ""  # LLM reasoning content
    observation: str = ""  # Observation content

    # Tool-related fields
    tool: str = ""  # Name of the called tool
    tool_input: dict = Field(default_factory=dict)  # Input to the tool

    # Message-related data
    message: list[dict] = Field(default_factory=dict)  # Message list used for reasoning
    message_token_count: int = 0  # Token count for messages
    message_unit_price: float = 0  # Unit price
    message_price_unit: float = 0  # Price unit

    # Answer-related data
    answer: str = ""  # Final answer generated by the LLM
    answer_token_count: int = 0  # Token count for the generated answer
    answer_unit_price: float = 0  # Unit price
    answer_price_unit: float = 0  # Price unit

    # Agent reasoning statistics
    total_token_count: int = 0  # Total token consumption
    total_price: float = 0  # Total cost
    latency: float = 0  # Latency of this reasoning step


class AgentResult(BaseModel):
    """Final result of agent reasoning and observation"""
    # TODO: Agent block content response, to be implemented after the Open API module is completed
    pass
