#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@File    : queue_entity.py
"""
from enum import Enum
from uuid import UUID

from pydantic import BaseModel, Field


class QueueEvent(str, Enum):
    """Queue event enumeration type"""
    LONG_TERM_MEMORY_RECALL = "long_term_memory_recall"  # Long-term memory recall event
    AGENT_THOUGHT = "agent_thought"  # Agent reasoning event
    AGENT_MESSAGE = "agent_message"  # Agent message event
    AGENT_ACTION = "agent_action"  # Agent action event
    DATASET_RETRIEVAL = "dataset_retrieval"  # Knowledge base retrieval event
    AGENT_END = "agent_end"  # Agent end event
    STOP = "stop"  # Agent stop event
    ERROR = "error"  # Agent error event
    TIMEOUT = "timeout"  # Agent timeout event
    PING = "ping"  # Ping connectivity event


class AgentQueueEvent(BaseModel):
    """Agent queue event model"""
    id: UUID  # ID corresponding to the event; identical for the same event
    task_id: UUID  # Task ID

    # Reasoning and observation fields
    event: QueueEvent
    thought: str = ""  # LLM reasoning content
    observation: str = ""  # Observation content

    # Tool-related fields
    tool: str = ""  # Name of the invoked tool
    tool_input: dict = Field(default_factory=dict)  # Input parameters for the tool

    # Message-related data
    message: list[dict] = Field(default_factory=dict)  # List of messages used during reasoning
    message_token_count: int = 0  # Token count consumed by messages
    message_unit_price: float = 0  # Unit price per message token
    message_price_unit: float = 0  # Price unit for message tokens

    # Answer-related data
    answer: str = ""  # Final answer generated by the LLM
    answer_token_count: int = 0  # Token count for the generated answer
    answer_unit_price: float = 0  # Unit price per answer token
    answer_price_unit: float = 0  # Price unit for answer tokens

    # Agent reasoning statistics
    total_token_count: int = 0  # Total token consumption
    total_price: float = 0  # Total cost
    latency: float = 0  # Time taken for the reasoning step
